### ISSUE TITLE
Specialist Report

### ISSUE THREAD

**Issue by KevinKuhlman** [DreamDevs/demo-web-project#4]
Create a page for the Specialist Reports to be entered. Page must be able to: Present list of Specialist reports with fields for choosing appropriate diagnoses, Ask for the dates of each taken Specialist report, store the values presented by the user, and be able to send the data to other classes for calculations.

**Comment by KevinKuhlman** [comment]
As a coder I want to develop the back-end functions for this class and help Celine in creating the front-end functions so that we can receive the appropriate information from the user and be able to process it in the future.

**Comment by KevinKuhlman** [comment]
Need to add an easier way to access all the names of the tests/diagnoses. Will likely create some Arrays or ArrayList to hold these values.

**Comment by chunhho** [comment]
Issue resolved.
